### ISSUE TITLE
Problem 5

### ISSUE THREAD

**Issue by jalotra** [Kavit900/codechef-Break-the-server#1]
Will there be a solution for Problem 5 ?

**Comment by Kavit900** [comment]
Hi @jalotra I haven't got time to try, I tried attempting the contest virtually and timed how many question can I solve within an hour, but I will surely give it a shot before another upcoming context on Codechef Div 3 - https://www.codechef.com/CCRC2021?itm_campaign=contest_listing . Thanks for opening an issue for this problem.

**Comment by jalotra** [comment]
Cool, I am also trying the same question. Will do a pull request if I will be able to get that.

**Comment by Kavit900** [comment]
#2 merged in, closing this issue
